# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-09 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180409_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='metatag',
            field=models.CharField(default='metatag', max_length=300),
        ),
    ]
